{
    "name": "Maxx Torrent Mirror",
    "description": "Telegram mirror bot with python",
    "logo": "https://telegra.ph/file/e15e9ac9c5885b015e3ab.jpg",
    "keywords": [
      "telegram",
      "bot",
      "aria",
      "python"
    ],
    "repository": "https://github.com/MaxxRider/Maxx-Torrent-Mirror-V2",
    "website": "https://github.com/MaxxRider/Maxx-Torrent-Mirror-V2/tree/main",
    "success_url": "https://github.com/MaxxRider/Maxx-Torrent-Mirror-V2/blob/main/README.md",
    "stack": "container",
    "env": {
      "ENV": {
      "description": "Setting this to ANYTHING will enable webhooks when in env mode",
      "value": "ANYTHING"
    },
      "BOT_TOKEN": {
        "description": "The telegram bot token that you get from @BotFather.",
        "required": true
      },
      "GDRIVE_FOLDER_ID": {
        "description": "This is the folder ID of the Google Drive Folder to which you want to upload all the mirrors.",
        "required": true
      },
      "DOWNLOAD_DIR": {
        "description": "The path to the local folder where the downloads should be downloaded to.",
        "required": true
      },
      "DOWNLOAD_STATUS_UPDATE_INTERVAL": {
        "description": "A short interval of time in seconds after which the Mirror progress message is updated. (I recommend to keep it 5 seconds at least).",
        "value": "5",
        "required":false
      },
      "OWNER_ID": {
        "description": "The Telegram user ID (not username) of the owner of the bot.",
        "required": true
      },
      "AUTH_CHATS": {
      "description": "chat ids which you wanted to authorize",
      "value": "608679953",
       "required": false
     },
      "AUTO_DELETE_MESSAGE_DURATION": {
        "description": "Interval of time (in seconds), after which the bot deletes it's message (and command message) which is expected to be viewed instantly. Note: Set to -1 to never automatically delete messages.",
        "required": true
      },
      "IS_TEAM_DRIVE": {
        "description": "Set to 'True' if GDRIVE_FOLDER_ID is from a Team Drive else False or Leave it empty.",
        "required": false
      },
      "USE_SERVICE_ACCOUNTS": {
        "description": "Whether to use service accounts or not. For this to work see 'Using service accounts' section below.",
        "required": false
      },
      "INDEX_URL": {
        "description": "Refer to https://github.com/maple3142/GDIndex/ The URL should not have any trailing '/'.",
        "required": false
      },
      "TELEGRAM_API": {
        "description": "This is to authenticate to your telegram account for downloading Telegram files. You can get this from https://my.telegram.org DO NOT put this in quotes.",
        "required": true
      },
      "TELEGRAM_HASH": {
        "description": "This is to authenticate to your telegram account for downloading Telegram files. You can get this from https://my.telegram.org.",
        "required": true
      },
      "TELEGRAPH_TOKEN": {
        "description": "Generate using python3 generate_telegraph_token.py.",
        "required": false
      },
      "MEGA_API_KEY": {
        "description": "To authenticate Mega.",
        "required": false
      },
      "MEGA_EMAIL_ID": {
        "description": "Mega Email.",
        "required": false
      },
      "MEGA_PASSWORD": {
        "description": "Mega Password.",
        "required": false
      },
      "SECRET_JSON": {
      "description": "Get it by running python3 generate_drive_token.py",
      "value": ""
    },
      "USER_SESSION_STRING": {
        "description": "    Session string generated by running: python3 generate_string_session.py in console heroku.",
        "required": true
      }
    }
}
